"""QEC code catalog, loaded from the generated single source.

The catalog is defined once in ``src/contracts/qec-code.ts`` and emitted to
``schemas/qec-code-catalog.json`` and the packaged copy alongside it. This
module reads that file rather than keeping a second hand-maintained copy.

Two hand-maintained copies drift. A drifted JSON Schema already caused a real
failure in this repository, where the runner rejected a manifest the TypeScript
contract accepted and the error named the field rather than the staleness. A
drifted *scientific* catalog would be worse, because it looks authoritative
while being wrong.

What the catalog deliberately does not do:

* It does not reproduce any external catalog's data or prose. Entries are
  structural facts in the project's own words; external catalogs are pointers.
* It does not emit recommendations. Suitability is derived from a hardware
  snapshot's capability fields so the claim can be checked, and capability
  matching never reports SIMULATED or DEMONSTRATED -- only a recorded run can
  raise the level that far.
"""
from __future__ import annotations

import json
from dataclasses import dataclass, field
from functools import lru_cache
from importlib import resources
from pathlib import Path
from typing import Any

CATALOG_FILENAME = "qec-code-catalog.json"

#: Structural families. A code may belong to several: the surface code is
#: stabilizer, CSS, and topological at once.
CODE_FAMILIES = (
    "STABILIZER", "CSS", "SUBSYSTEM", "TOPOLOGICAL", "SURFACE", "TORIC", "COLOR",
    "QUANTUM_LDPC", "HYPERGRAPH_PRODUCT", "BIVARIATE_BICYCLE", "CONCATENATED",
    "BOSONIC", "GKP", "CAT", "QUDIT", "ERASURE_TOLERANT", "APPROXIMATE", "FLOQUET",
)

#: Ordered weakest to strongest. The negative and unknown cases stay distinct:
#: "we do not know" and "this does not work" are different statements.
SUITABILITY_LEVELS = (
    "UNKNOWN",
    "INCOMPATIBLE_UNDER_ASSUMPTIONS",
    "REQUIRES_NONLOCAL_CONNECTIVITY",
    "REQUIRES_FAST_FEEDFORWARD",
    "REQUIRES_LOSS_DETECTION",
    "THEORETICALLY_SUITABLE",
    "SIMULATED",
    "DEMONSTRATED",
    "COMPATIBLE",
)


@dataclass(frozen=True)
class QecCode:
    """A code family entry.

    The ``requires_*`` fields exist so suitability can be *derived* from a
    hardware snapshot rather than asserted, which keeps the claim checkable.
    """

    slug: str
    name: str
    families: tuple[str, ...]
    description: str
    requires_mid_circuit_measurement: bool = True
    requires_feed_forward: bool = False
    requires_nonlocal_connectivity: bool = False
    requires_loss_detection: bool = False
    supported_distances: tuple[int, ...] = ()
    stim_generator: str | None = None
    references: tuple[str, ...] = ()
    notes: tuple[str, ...] = field(default_factory=tuple)


def _catalog_path() -> Path:
    packaged = resources.files("ketqat_runner").joinpath("schemas", CATALOG_FILENAME)
    if packaged.is_file():
        with resources.as_file(packaged) as path:
            return path
    for parent in Path(__file__).resolve().parents:
        candidate = parent / "schemas" / CATALOG_FILENAME
        if candidate.is_file():
            return candidate
    raise FileNotFoundError(
        f"{CATALOG_FILENAME} not found. It is generated by `npm run build` in the SDK root."
    )


@lru_cache(maxsize=1)
def _load_catalog() -> dict[str, QecCode]:
    payload = json.loads(_catalog_path().read_text(encoding="utf-8"))
    codes: dict[str, QecCode] = {}
    for entry in payload["codes"]:
        codes[entry["slug"]] = QecCode(
            slug=entry["slug"],
            name=entry["name"],
            families=tuple(entry["families"]),
            description=entry["description"],
            requires_mid_circuit_measurement=entry.get("requires_mid_circuit_measurement", True),
            requires_feed_forward=entry.get("requires_feed_forward", False),
            requires_nonlocal_connectivity=entry.get("requires_nonlocal_connectivity", False),
            requires_loss_detection=entry.get("requires_loss_detection", False),
            supported_distances=tuple(entry.get("supported_distances", ())),
            stim_generator=entry.get("stim_generator"),
            references=tuple(entry.get("references", ())),
            notes=tuple(entry.get("notes", ())),
        )
    return codes


class _CatalogMapping(dict):
    """Lazy view over the generated catalog, so imports stay cheap."""

    def __getitem__(self, key: str) -> QecCode:
        return _load_catalog()[key]

    def get(self, key: str, default: Any = None) -> Any:
        return _load_catalog().get(key, default)

    def __iter__(self):
        return iter(_load_catalog())

    def __len__(self) -> int:
        return len(_load_catalog())

    def values(self):
        return _load_catalog().values()

    def items(self):
        return _load_catalog().items()

    def keys(self):
        return _load_catalog().keys()

    def __contains__(self, key: object) -> bool:
        return key in _load_catalog()


CATALOG: dict[str, QecCode] = _CatalogMapping()


def get_code(slug: str) -> QecCode:
    codes = _load_catalog()
    code = codes.get(slug)
    if code is None:
        raise KeyError(f"Unknown QEC code {slug!r}. Known codes: {', '.join(sorted(codes))}.")
    return code


def codes_in_family(family: str) -> list[QecCode]:
    upper = family.upper()
    return [code for code in _load_catalog().values() if upper in code.families]


def assess_suitability(code: QecCode, capabilities: dict[str, Any]) -> dict[str, Any]:
    """Derive a code/hardware suitability level from a hardware snapshot.

    Mirrors ``assessQecSuitability`` in the TypeScript contracts; both read the
    same catalog, and a parity test asserts the two agree.
    """
    blockers: list[str] = []
    level = "THEORETICALLY_SUITABLE"

    if code.requires_mid_circuit_measurement and not capabilities.get("mid_circuit_measurement"):
        blockers.append("mid-circuit measurement is required for syndrome extraction")
        level = "INCOMPATIBLE_UNDER_ASSUMPTIONS"
    if code.requires_feed_forward and not capabilities.get("feed_forward"):
        blockers.append("classical feed-forward is required")
        level = "REQUIRES_FAST_FEEDFORWARD"
    if code.requires_nonlocal_connectivity and not (
        capabilities.get("all_to_all_connectivity") or capabilities.get("dynamic_connectivity")
    ):
        blockers.append("non-local connectivity is required")
        level = "REQUIRES_NONLOCAL_CONNECTIVITY"
    if code.requires_loss_detection and not (
        capabilities.get("loss_detection") or capabilities.get("erasure_conversion")
    ):
        blockers.append("loss or erasure detection is required")
        level = "REQUIRES_LOSS_DETECTION"

    return {
        "code": code.slug,
        "level": level,
        "blockers": blockers,
        "evidence": (
            "Derived from the capability fields of the supplied hardware snapshot. This is a "
            "capability match, not an experimental result: only a recorded run may raise the "
            "level to SIMULATED or DEMONSTRATED."
        ),
    }
