"""The record-kind shape tables, read rather than restated.

The classification lives once, in `src/study/registry.ts`, where
`tests/study-field-completeness.test.mjs` walks each Zod schema against it and
fails on any field it does not classify, in either direction. That test is what
makes an allowlist safe rather than merely different, and it can only watch one
copy of the tables.

So this module loads the copy `scripts/generate-study-shapes.mjs` emits, rather
than carrying a second hand-written copy that the completeness test would not be
watching and that could drift from the schemas without anything failing. The two
emitted copies -- the repository's `schemas/` and the packaged one here -- are
checked against each other by `npm run verify:schema-sync`, for the same reason
the JSON Schemas are.

Resolution order matches `validation.py`: the packaged copy first, because that
is what actually runs for an installed runner, then the repository's.
"""

from __future__ import annotations

import json
from importlib import resources
from pathlib import Path
from types import MappingProxyType
from typing import Any, Mapping

from .study_limits import refuse

_SHAPES_FILENAME = "study-record-shapes.json"


def _shapes_path() -> Path:
    package_path = resources.files("ketqat_runner").joinpath("schemas", _SHAPES_FILENAME)
    if package_path.is_file():
        with resources.as_file(package_path) as path:
            return path
    for parent in Path(__file__).resolve().parents:
        candidate = parent / "schemas" / _SHAPES_FILENAME
        if candidate.is_file():
            return candidate
    raise FileNotFoundError(
        f"{_SHAPES_FILENAME} was not found. It is generated by `npm run build`; without it this module "
        "cannot project a record, and guessing a shape would be inventing a digest."
    )


_DOCUMENT: Mapping[str, Any] = json.loads(_shapes_path().read_text(encoding="utf-8"))

#: Every record kind this build hashes, as immutable plain data.
STUDY_RECORD_KINDS: tuple[Mapping[str, Any], ...] = tuple(
    MappingProxyType(entry) for entry in _DOCUMENT["record_kinds"]
)

#: The record kind names, as immutable plain data.
STUDY_RECORD_KIND_NAMES: tuple[str, ...] = tuple(
    entry["record_kind"] for entry in STUDY_RECORD_KINDS
)

#: The kinds this build knows and deliberately does not hash, as immutable data.
#:
#: An ``execution_job`` is queue status, an attempt counter, a progress figure
#: and a cancellation flag: every one of them is overwritten while the work runs,
#: which is exactly what a content address cannot survive. Read from the emitted
#: tables rather than restated here, so the two languages give the same answer to
#: "why will you not hash this".
STUDY_CONTROL_PLANE_KINDS: tuple[Mapping[str, Any], ...] = tuple(
    MappingProxyType(entry) for entry in _DOCUMENT.get("control_plane_kinds", ())
)

#: The control-plane kind names, as immutable plain data.
STUDY_CONTROL_PLANE_KIND_NAMES: tuple[str, ...] = tuple(
    entry["record_kind"] for entry in STUDY_CONTROL_PLANE_KINDS
)

#: The working lookups, module-private and built from the published tuples.
_KINDS_BY_NAME = {entry["record_kind"]: entry for entry in STUDY_RECORD_KINDS}
_CONTROL_PLANE_BY_NAME = {entry["record_kind"]: entry for entry in STUDY_CONTROL_PLANE_KINDS}


def study_record_kind(record_kind: str) -> Mapping[str, Any]:
    """The entry for a record kind, or a refusal.

    A dict lookup with an explicit miss rather than ``getattr`` or a class
    hierarchy: a record kind is a preimage header component, so an unknown one is
    a digest namespace nobody declared rather than a record to hash under a
    guess.

    A control-plane kind gets its own code. "We do not hash this" and "we have
    never heard of this" send a reader to two different places, and the second
    answer for the first question would send them looking for a missing
    declaration instead of at the record they should be addressing.
    """
    entry = _KINDS_BY_NAME.get(record_kind)
    if entry is None:
        control_plane = _CONTROL_PLANE_BY_NAME.get(record_kind)
        if control_plane is not None:
            refuse(
                "NOT_CONTENT_ADDRESSED",
                f"{record_kind!r} is control-plane state and this family does not hash it: "
                f"{control_plane['why']}. Reference {control_plane['address_instead']} instead, "
                "whose digest does not move while the work runs.",
            )
        refuse(
            "UNKNOWN_RECORD_KIND",
            f"this build does not know the record kind {record_kind!r}. Known kinds: "
            f"{', '.join(STUDY_RECORD_KIND_NAMES)}.",
        )
    return entry


def study_shape_document() -> Mapping[str, Any]:
    """The whole emitted document, for the parity tests to compare against."""
    return MappingProxyType(_DOCUMENT)
