import type { Decoder } from "./types.js"

export const mockDecoders: Decoder[] = [
  {
    id: "union-find-decoder",
    title: "Union-Find Decoder",
    author: "quantum-research-lab",
    description: "Efficient decoder for surface codes using union-find data structure. Provides fast error correction with O(n log n) complexity.",
    stars: 1247,
    downloads: 8932,
    tags: ["surface-code", "union-find", "efficient", "python"],
    codeType: "surface-code",
    qubitType: "superconducting",
    distance: 5,
    createdAt: "2023-01-15",
    updatedAt: "2024-03-20",
    language: "Python",
    license: "MIT",
  },
  {
    id: "mwpm-decoder",
    title: "Minimum Weight Perfect Matching (MWPM)",
    author: "qec-team",
    description: "Classical MWPM decoder for surface codes. Implements the standard minimum weight perfect matching algorithm for error correction.",
    stars: 2156,
    downloads: 15234,
    tags: ["surface-code", "mwpm", "classical", "c++"],
    codeType: "surface-code",
    qubitType: "superconducting",
    distance: 7,
    createdAt: "2022-08-10",
    updatedAt: "2024-02-14",
    language: "C++",
    license: "Apache 2.0",
  },
  {
    id: "surface-code-rotated",
    title: "Rotated Surface Code Decoder",
    author: "quantum-algorithms",
    description: "Specialized decoder for rotated surface codes with improved threshold performance. Optimized for near-term quantum devices.",
    stars: 892,
    downloads: 5432,
    tags: ["surface-code", "rotated", "threshold", "optimized"],
    codeType: "surface-code",
    qubitType: "trapped-ion",
    distance: 3,
    createdAt: "2023-05-22",
    updatedAt: "2024-01-08",
    language: "Python",
    license: "MIT",
  },
  {
    id: "color-code-decoder",
    title: "Color Code Decoder",
    author: "topological-qec",
    description: "Decoder for color codes with improved error thresholds. Supports both 6-6-6 and 4-8-8 color code lattices.",
    stars: 634,
    downloads: 3210,
    tags: ["color-code", "topological", "threshold", "lattice"],
    codeType: "color-code",
    qubitType: "superconducting",
    distance: 5,
    createdAt: "2023-09-12",
    updatedAt: "2024-03-05",
    language: "Python",
    license: "GPL-3.0",
  },
  {
    id: "neural-decoder",
    title: "Neural Network Decoder",
    author: "ml-quantum",
    description: "Machine learning-based decoder using neural networks. Trained on surface code syndromes for improved error correction rates.",
    stars: 1843,
    downloads: 9876,
    tags: ["neural-network", "machine-learning", "surface-code", "pytorch"],
    codeType: "surface-code",
    qubitType: "all",
    distance: 5,
    createdAt: "2023-11-03",
    updatedAt: "2024-04-12",
    language: "Python",
    license: "MIT",
  },
  {
    id: "bosonic-cat-code",
    title: "Bosonic Cat Code Decoder",
    author: "bosonic-qec",
    description: "Decoder for bosonic cat codes using continuous-variable quantum error correction. Optimized for photonic quantum systems.",
    stars: 456,
    downloads: 2134,
    tags: ["bosonic", "cat-code", "photonic", "continuous-variable"],
    codeType: "bosonic",
    qubitType: "photonic",
    distance: 3,
    createdAt: "2023-07-18",
    updatedAt: "2024-02-28",
    language: "Python",
    license: "MIT",
  },
  {
    id: "repetition-code-decoder",
    title: "Repetition Code Decoder",
    author: "quantum-basics",
    description: "Simple decoder for quantum repetition codes. Ideal for educational purposes and small-scale error correction.",
    stars: 312,
    downloads: 1876,
    tags: ["repetition-code", "simple", "educational", "beginner"],
    codeType: "stabilizer",
    qubitType: "all",
    distance: 3,
    createdAt: "2023-12-01",
    updatedAt: "2024-01-15",
    language: "Python",
    license: "MIT",
  },
  {
    id: "lattice-surgery-decoder",
    title: "Lattice Surgery Decoder",
    author: "topological-computing",
    description: "Advanced decoder for lattice surgery operations on surface codes. Enables fault-tolerant quantum computation.",
    stars: 1023,
    downloads: 6543,
    tags: ["lattice-surgery", "surface-code", "fault-tolerant", "advanced"],
    codeType: "surface-code",
    qubitType: "superconducting",
    distance: 7,
    createdAt: "2023-03-25",
    updatedAt: "2024-03-18",
    language: "C++",
    license: "Apache 2.0",
  },
  {
    id: "trapped-ion-surface",
    title: "Trapped-Ion Surface Code Decoder",
    author: "ion-quantum",
    description: "Specialized decoder optimized for trapped-ion quantum computers. Accounts for ion-specific noise characteristics.",
    stars: 567,
    downloads: 3456,
    tags: ["trapped-ion", "surface-code", "noise-aware", "specialized"],
    codeType: "surface-code",
    qubitType: "trapped-ion",
    distance: 5,
    createdAt: "2023-10-08",
    updatedAt: "2024-02-22",
    language: "Python",
    license: "MIT",
  },
  {
    id: "stabilizer-simulator",
    title: "Stabilizer Code Simulator & Decoder",
    author: "quantum-sim",
    description: "Comprehensive stabilizer code simulator with built-in decoder. Supports various stabilizer codes and error models.",
    stars: 789,
    downloads: 4321,
    tags: ["stabilizer", "simulator", "error-models", "comprehensive"],
    codeType: "stabilizer",
    qubitType: "all",
    distance: 5,
    createdAt: "2023-06-14",
    updatedAt: "2024-03-10",
    language: "Python",
    license: "GPL-3.0",
  },
]

export function getDecoderById(id: string): Decoder | undefined {
  return mockDecoders.find((decoder) => decoder.id === id)
}

export function getTrendingDecoders(limit: number = 6): Decoder[] {
  return [...mockDecoders]
    .sort((a, b) => b.stars - a.stars)
    .slice(0, limit)
}

